/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2020-04-20 12:29:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AllChains_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/wkdan/Desktop/final_iot/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/top/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1575513783315L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://code.highcharts.com/highcharts.js\"></script>\n");
      out.write("<script src=\"https://code.highcharts.com/modules/exporting.js\"></script>\n");
      out.write("<script src=\"https://code.highcharts.com/modules/export-data.js\"></script>\n");
      out.write("<script src=\"https://code.highcharts.com/modules/accessibility.js\"></script>\n");
      out.write("<style>\n");
      out.write("#container_highcharts {\n");
      out.write("\theight: 400px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".highcharts-figure, .highcharts-data-table table {\n");
      out.write("\tmin-width: 310px;\n");
      out.write("\tmax-width: 800px;\n");
      out.write("\tmargin: 1em auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".highcharts-data-table table {\n");
      out.write("\tfont-family: Verdana, sans-serif;\n");
      out.write("\tborder-collapse: collapse;\n");
      out.write("\tborder: 1px solid #EBEBEB;\n");
      out.write("\tmargin: 10px auto;\n");
      out.write("\ttext-align: center;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tmax-width: 500px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".highcharts-data-table caption {\n");
      out.write("\tpadding: 1em 0;\n");
      out.write("\tfont-size: 1.2em;\n");
      out.write("\tcolor: #555;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".highcharts-data-table th {\n");
      out.write("\tfont-weight: 600;\n");
      out.write("\tpadding: 0.5em;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".highcharts-data-table td, .highcharts-data-table th,\n");
      out.write("\t.highcharts-data-table caption {\n");
      out.write("\tpadding: 0.5em;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".highcharts-data-table thead tr, .highcharts-data-table tr:nth-child(even)\n");
      out.write("\t{\n");
      out.write("\tbackground: #f8f8f8;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".highcharts-data-table tr:hover {\n");
      out.write("\tbackground: #f1f7ff;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("\tfunction display() {\n");
      out.write("\n");
      out.write("\t\tHighcharts\n");
      out.write("\t\t\t\t.chart(\n");
      out.write("\t\t\t\t\t\t'container_highcharts',\n");
      out.write("\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\tchart : {\n");
      out.write("\t\t\t\t\t\t\t\ttype : 'column'\n");
      out.write("\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\ttitle : {\n");
      out.write("\t\t\t\t\t\t\t\ttext : 'Today\\'s Total Sales for All Chains'\n");
      out.write("\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\txAxis : {\n");
      out.write("\t\t\t\t\t\t\t\ttype : 'category',\n");
      out.write("\t\t\t\t\t\t\t\tlabels : {\n");
      out.write("\t\t\t\t\t\t\t\t\trotation : -45,\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle : {\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfontSize : '13px',\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfontFamily : 'Verdana, sans-serif'\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\tyAxis : {\n");
      out.write("\t\t\t\t\t\t\t\tmin : 0,\n");
      out.write("\t\t\t\t\t\t\t\ttitle : {\n");
      out.write("\t\t\t\t\t\t\t\t\ttext : 'Total Sales(Ten thousand KRW)'\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\tlegend : {\n");
      out.write("\t\t\t\t\t\t\t\tenabled : false\n");
      out.write("\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\ttooltip : {\n");
      out.write("\t\t\t\t\t\t\t\tpointFormat : 'Population in 2017: <b>{point.y:.1f} millions</b>'\n");
      out.write("\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\tseries : [ {\n");
      out.write("\t\t\t\t\t\t\t\tname : 'Population',\n");
      out.write("\t\t\t\t\t\t\t\tdata : [ [ 'Shanghai', 24.2 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Beijing', 20.8 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Karachi', 14.9 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Shenzhen', 13.7 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Guangzhou', 13.1 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Istanbul', 12.7 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Mumbai', 12.4 ], [ 'Moscow', 12.2 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'S찾o Paulo', 12.0 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Delhi', 11.7 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Kinshasa', 11.5 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Tianjin', 11.2 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Lahore', 11.1 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Jakarta', 10.6 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Dongguan', 10.6 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Lagos', 10.6 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Bengaluru', 10.3 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Seoul', 9.8 ], [ 'Foshan', 9.3 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 'Tokyo', 9.3 ] ],\n");
      out.write("\t\t\t\t\t\t\t\tdataLabels : {\n");
      out.write("\t\t\t\t\t\t\t\t\tenabled : true,\n");
      out.write("\t\t\t\t\t\t\t\t\trotation : -90,\n");
      out.write("\t\t\t\t\t\t\t\t\tcolor : '#FFFFFF',\n");
      out.write("\t\t\t\t\t\t\t\t\talign : 'right',\n");
      out.write("\t\t\t\t\t\t\t\t\tformat : '{point.y:.1f}', // one decimal\n");
      out.write("\t\t\t\t\t\t\t\t\ty : 10, // 10 pixels down from the top\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle : {\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfontSize : '13px',\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfontFamily : 'Verdana, sans-serif'\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t} ]\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t};\n");
      out.write("\n");
      out.write("\t/* function getData() {\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl : '',\n");
      out.write("\t\t\tsuccess : function(data) {\n");
      out.write("\t\t\t\tdisplay(data);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t};\n");
      out.write("\t */\n");
      out.write("\t$(document).ready(function() {\n");
      out.write("\t\tdisplay();\n");
      out.write("\t\t//getData();\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("<h1 class=\"page-title\">Main Page</h1>\n");
      out.write("<div class=\"card\">\n");
      out.write("\t<div class=\"card-body\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-5 col-md-4\">\n");
      out.write("\t\t\t\t<div class=\"nav flex-column nav-pills nav-secondary\"\n");
      out.write("\t\t\t\t\tid=\"v-pills-tab\" role=\"tablist\" aria-orientation=\"vertical\">\n");
      out.write("\t\t\t\t\t<a class=\"nav-link active\" id=\"v-pills-home-tab\" data-toggle=\"pill\"\n");
      out.write("\t\t\t\t\t\thref=\"#v-pills-home\" role=\"tab\" \n");
      out.write("\t\t\t\t\t\taria-controls=\"v-pills-home\"\n");
      out.write("\t\t\t\t\t\taria-selected=\"true\">All</a> \n");
      out.write("\t\t\t\t\t<a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\tid=\"v-pills-profile-tab\" data-toggle=\"pill\"\n");
      out.write("\t\t\t\t\t\thref=\"#v-pills-profile\" role=\"tab\" \n");
      out.write("\t\t\t\t\t\taria-controls=\"v-pills-profile\"\n");
      out.write("\t\t\t\t\t\taria-selected=\"false\">Chain01</a> \n");
      out.write("\t\t\t\t\t<a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\tid=\"v-pills-messages-tab\" data-toggle=\"pill\"\n");
      out.write("\t\t\t\t\t\thref=\"#v-pills-messages\" role=\"tab\"\n");
      out.write("\t\t\t\t\t\taria-controls=\"v-pills-messages\" aria-selected=\"false\">Chain02</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-7 col-md-8\">\n");
      out.write("\t\t\t\t<div class=\"highcharts-figure\">\n");
      out.write("\t\t\t\t\t<div id=\"container_highcharts\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<h1 class=\"card-sub\">Chart License: Highcharts.com</h1>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
